name: backup CodeFolder
on:
  workflow_call:
    inputs:
      remotedir:
        required: true
        type: string
      ip_machines:
        description: maquinas por ip, paraleliza con el job matrix y el strategy
        required: true
        type: string

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: |
          ${{ steps.matrix.outputs.matrix }}        
    steps:
        - name: Outputs matrix
          id: matrix
          run: |
              ips="${{ inputs.ip_machines }}"
              matrix=$(echo $ips | jq -cR 'split (",") | .[]' | jq -s '[.[] | { machine: . }]' | jq -c '{ include: . }')
              echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  # Hacer Housekeeping de los backups que contengan el basename del remotedir
  HousekeepingBackups:
    name: Housekeeping Backups
    needs: [matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
    - name: executing remote ssh commands using ssh key
      run: |
        echo ${{ matrix.machine }}
        echo ${{ inputs.remotedir }}
        
  BackupCodeFolder:
    name: Backup CodeFolder
    needs: [HousekeepingBackups,matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
    - name: executing remote ssh commands using ssh key
      run: |
        echo ${{ matrix.machine }}
        echo ${{ inputs.remotedir }}
