name: restart PHP
on:
  workflow_call:
    inputs:
      remotedir:
        required: true
        type: string
      ip_machines:
        description: maquinas por ip, paraleliza con el job matrix y el strategy
        required: true
        type: string
      consolefolder:
        description: Puede ser app/console - bin/console
        type: string
        default: 'bin/console'
      entorno:
        description: Puede tener valores para "vacio", "pre" y "prod"
        type: string
        default: ''

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: |
          ${{ steps.matrix.outputs.matrix }}        
    steps:
        - name: Outputs matrix
          id: matrix
          run: |
              ips="${{ inputs.ip_machines }}"
              matrix=$(echo $ips | jq -cR 'split (",") | .[]' | jq -s '[.[] | { machine: . }]' | jq -c '{ include: . }')
              echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  ConnectAndRestartPHP:
    name: Ejecuta Cache:Clear
    needs: [matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
    - name: executing remote ssh commands using ssh key
      run: |
        echo ${{ matrix.machine }}
        echo ${{ inputs.remotedir }}
        echo ${{ inputs.consolefolder }}
        echo ${{ inputs.entorno }}
